#if !canImport(ObjectiveC)
import XCTest

extension CancellerTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CancellerTests = [
        ("testAddSubcanceller", testAddSubcanceller),
        ("testCancel", testCancel),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(CancellerTests.__allTests__CancellerTests),
    ]
}
#endif
