#if !canImport(ObjectiveC)
import XCTest

extension GameControllerTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__GameControllerTests = [
        ("testComputers", testComputers),
        ("testInit", testInit),
        ("testPlaceDisk", testPlaceDisk),
        ("testReset", testReset),
        ("testSetPlayer", testSetPlayer),
        ("testStart", testStart),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(GameControllerTests.__allTests__GameControllerTests),
    ]
}
#endif
