#if !canImport(ObjectiveC)
import XCTest

extension BoardAnimationTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BoardAnimationTests = [
        ("testUpdateDisk", testUpdateDisk),
    ]
}

extension BoardDiffTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BoardDiffTests = [
        ("testBoardDiff", testBoardDiff),
    ]
}

extension GameControllerTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__GameControllerTests = [
        ("testComputers", testComputers),
        ("testInit", testInit),
        ("testPlaceDisk", testPlaceDisk),
        ("testReset", testReset),
        ("testSetPlayer", testSetPlayer),
        ("testStart", testStart),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(BoardAnimationTests.__allTests__BoardAnimationTests),
        testCase(BoardDiffTests.__allTests__BoardDiffTests),
        testCase(GameControllerTests.__allTests__GameControllerTests),
    ]
}
#endif
